use threading to fix time timeout problem
laixintao/prometheus-http-sd pull request #39
Opened 2023-04-14 01:30 UTC by karta0807913

1. Set timeout to the target function
2. Reduce the impact of multiple queries

2023-04-14 03:01 UTC, laixintao requested changes
It's generally a very good implementation.

Actually there is already an [implementation](https://github.com/python/cpython/blob/3fc5d84046ddbd66abac5b598956ea34605a4e5d/Lib/functools.py#L525) based on double linked list, considered all the details, and it's usage is very simple: https://docs.python.org/3/library/functools.html#functools.lru_cache , I prefer to use this one, the only issue is that, it's not "timed", only evict items when the `maxsize` reached, which is not good for our service discovery case. Some solutions [here](https://stackoverflow.com/questions/31771286/python-in-memory-cache-with-time-to-live).

The `threading.join()` implementation for timeout is excellent. But I saw that we only simply check if the thread is finished or not, without killing it. I don't have any ideas on that, maybe killing a thread is generally a bad idea, so maybe we only give a lock to every script so that even the thread is not terminated we only have one thread running per script? Python's built in `lru_cache` also didn't lock functions, means there could be same exactly function running at the same time.

2023-04-14 03:06 UTC, laixintao commented on test/test_timeout/test_timeout.py
> +    assert first_call == second_call, "the function did't cache the result :("
so can use `object()` to replace `random`

2023-04-14 03:17 UTC, karta0807913 commented on prometheus_http_sd/sd.py
> +            with lock:
yes, but I only do a little job in the lock, so I think it won't affect so much.

2023-04-14 03:17 UTC, karta0807913 commented on prometheus_http_sd/sd.py
> +                        cache = thread_cache[key]
make sense. let me use another thread to clean them.

2023-04-14 05:53 UTC, karta0807913 commented
I refrained from utilizing the `lru_cache` due to the potential variability of the target generator over time. If a URL is repeatedly called, the cache will not expire, causing the targets to remain static. This would not be beneficial for our monitoring virtual machines. Also, the `lru_cache` function is not thread-safe. Therefore, I prefer using the time-based cache to handle the cache.

```
import time
import functools
import threading

@functools.lru_cache
def cache_function():
    time.sleep(10)
    print("HI")
    return 2

threading.Thread(target=cache_function).start()
threading.Thread(target=cache_function).start()
threading.Thread(target=cache_function).start()
```

output is
```
HI
HI
HI
```

Therefore, I used a lock inside the decorator to use the same thread for the cache -- this won't affect the users so much :D
Users still can call the function parallelly, because the "thread.wait()" is outside of the lock scope. The lock scope only controls the cache usage.

About the threading problem, Python not support stop the thread during the thread is executing (as same as another languages).
Also, not stopping the thread allow users can get the result after serval function calls. For example:
```
First Function call (timeout)
└─┘
Second Function call (timeout)
             └─┘
Third Function call(get result)
                       └─┘
Function Operating   Cache time
└───────────────────┴───────────┘
```

And I agree we should implement the garbage collection for this function. Let me implement it by using the heap :D

2023-04-14 09:12 UTC, karta0807913 commented on test/test_timeout/test_timeout.py
> +    assert first_call == second_call, "the function did't cache the result :("
done

2023-04-14 09:13 UTC, karta0807913 commented on prometheus_http_sd/sd.py
> +            if cache["error"] is not None:
done :D

2023-04-14 09:14 UTC, karta0807913 commented on prometheus_http_sd/sd.py
> +                        cache = thread_cache[key]
done, please help to review :D

2023-04-17 02:05 UTC, laixintao requested changes
Can you add metrics to those:

- last gc timestamp
- gc time count
- current cached item count

So we can monitor http-sd itself

2023-04-17 02:05 UTC, laixintao commented on prometheus_http_sd/decroator.py
> +        print(self.heap, can_iterate())
use logging module please

2023-04-17 02:17 UTC, karta0807913 commented
sure, let me add the metrics

2023-04-17 02:17 UTC, karta0807913 commented on prometheus_http_sd/decroator.py
> +        print(self.heap, can_iterate())
oh, I forgot to delete the test code LOL

2023-04-17 03:35 UTC, laixintao commented on prometheus_http_sd/decroator.py
> +        len(thread_cache): {self.thread_cache}""")
sorry, I didn't make myself clear, I mean, expose prometheus metrics, like this:

https://github.com/laixintao/prometheus-http-sd/blob/778dbbba5508dff96d7ff602865812574d3d8570/prometheus_http_sd/sd.py#L24

2023-04-18 03:24 UTC, laixintao requested changes

2023-04-18 03:24 UTC, laixintao commented on prometheus_http_sd/decroator.py
> +    "garbage_collection_run_interval",
```suggestion
     "http_sd_garbage_collection_run_interval_seconds_bucket",
```

there is a naming convention: https://prometheus.io/docs/practices/naming/

2023-04-18 03:24 UTC, laixintao commented on prometheus_http_sd/decroator.py
> +    "garbage_collection_collected_items",
```suggestion
    "httpsd_garbage_collection_collected_items_total",
```

2023-04-18 03:24 UTC, laixintao commented on prometheus_http_sd/decroator.py
> +    "garbage_collection_cache_count",
```suggestion
    "httpsd_garbage_collection_cache_count",
```

2023-04-18 03:24 UTC, laixintao commented on prometheus_http_sd/decroator.py
> +    "garbage_collection_heap_count",
```suggestion
    "httpsd_garbage_collection_heap_count",
```

2023-04-18 08:14 UTC, merged